config/routes.rb
Rails.application.routes.draw do
  root to: "planets#home"
  resources :planets do
    resources :bookings, only: [:create, :new]
    devise_for :users, only: [:create, :new]
  end
  resources :bookings, only: [:index, :destroy, :edit, :update]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :planet
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :bookings
  has_many :users, through: :bookings # utilisateurs ayant demander cette planète
  belongs_to :user # propriétaire
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :bookings_as_owner, through: :planets, source: :bookings # bookings on the planets that user owns
  has_many :planets # user planets

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user: current_user)
  end

  def new
    @booking = Booking.new
    @planet = Planet.find(params[:planet_id])
  end

  def create

    @planet = Planet.find(params[:planet_id])
    @booking = Booking.new(bookings_params)
    @booking.planet = @planet
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(bookings_params)
    redirect_to bookings_path
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date, :planet_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]


  def home
    @planets = Planet.all
    if params[:query].present?
      @planets = @planets.where("name ILIKE ?", "%#{params[:query]}%")
    end
  end

  def index
    @planets = Planet.where(user: current_user)
  end

  def show
  end

  def new
    @planet = Planet.new
  end

  def create
    @planet = Planet.new(planet_params)
    @planet.user = current_user
    if @planet.save
      redirect_to planet_path(@planet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @planet.update(planet_params)
    redirect_to planet_path(@planet)
  end

  def destroy
    @planet.destroy
    redirect_to planets_path, status: :see_other
  end

  private

  def planet_params
    params.require(:planet).permit(:detail, :name, :price, :photo)
  end

  def set_planet
    @planet = Planet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class = "mx-auto" style="width: 400px;">
  <%= simple_form_for [@planet, @booking] do |f| %>
    <%= f.input :start_date, input_html: { class: "rounded-5"} %>
    <%= f.input :end_date, input_html: { class: "rounded-5"} %>
    <%= f.submit class: "btn btn-dark border border-white rounded-5" %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="d-flex mt-5 m-3">
    <h1>Your bookings :</h1>
  </div>
  <div class="row">
    <% if @bookings.size == 0 %>
      <h1>You have no bookings...</h1>
    <% else %>
      <% @bookings.each do |booking| %>
        <div class="card-product col-4 ">
          <h2><%= booking.planet.name %> - <strong><%= booking.planet.price %>$</strong></h2>
          <% if booking.planet.photo.attached? %>
            <p><%= cl_image_tag booking.planet.photo.key, height: 200, width: 200, crop: :fill %></p>
          <% else %>
            <p><%= image_tag 'planet-par-defaut.png', height: 200, width: 200 %></p>
          <% end %>
            <div class="card-product-infos">
                <p>Du : <strong><%= booking.start_date %></strong></p>
                <p> Au : <strong><%= booking.end_date %></strong></p>
                <%= link_to "Delete", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-dark border border-white rounded-5 text-decoration-none"%>
                <%= link_to "Edit your booking", edit_booking_path(booking), class:"btn btn-dark border border-white rounded-5 text-decoration-none" %>
            </div>
        </div>
      <% end %>
    <% end %>
    </div>
</div>

app/views/bookings/new.html.erb
<div class="d-flex justify-content-center mt-5 mb-2">
    <h1>Your new booking</h1>
</div>

<div class = "mx-auto" style="width: 400px;">
  <%= simple_form_for [@planet, @booking] do |f| %>
    <%= f.input :start_date, input_html: { class: "rounded-5"} %>
    <%= f.input :end_date, input_html: { class: "rounded-5"} %>
    <%= f.submit class: "btn btn-dark border border-white rounded-5" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanetBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body class="body">
    <nav class="navbar">
      <div class="container fluid">
      <div class="logo_title">
        <%= image_tag "rocket-png-40798.png", class: "rocket", alt: "rocket"%>
        <h1><%= link_to "Planet bnb", root_path, class: "title-main" %></h1>
      </div>
      <div class="end-navbar">
        <%= link_to "Add a new planet", new_planet_path, class: "new-planet" %>
        <div class="drop-avatar">
            <%= image_tag "https://avatars.githubusercontent.com/u/165579109?v=4", class: "avatar", alt: "avatar" %>
          <div class="dropdown mr-5">
            <button class="btn btn-secondary rounded-pill bg-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-list"></i></button>
            <ul class="dropdown-menu rounded-5 dropdown-menu-end dropdown-menu-dark mt-3">
              <% if current_user == nil %>
                <li><%= link_to "Connexion", new_user_session_path, class:"btn dropdown-item" %></li>
                <li><%= link_to "Inscription", new_user_registration_path, class:"btn dropdown-item" %></li>
              <% else %>
                <li><%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn dropdown-item" %></li>
                <li><%= link_to "Mes réservations", bookings_path, class:"btn dropdown-item" %></li>
                <li><%= link_to "Mes planètes", planets_path, class:"btn dropdown-item" %></li>
              <% end %>
            </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/planets/_form.html.erb
<div class = "mx-auto" style="width: 400px;">
<%= simple_form_for(@planet) do |f| %>
  <%= f.input :name, input_html: { class: "rounded-5"} %>
  <%= f.input :detail, input_html: { class: "rounded-5"} %>
  <%= f.input :price, input_html: { class: "rounded-5"} %>
  <%= f.input :photo, as: :file, input_html: { class: "rounded-5"} %>
  <%= f.submit "create", class: "btn btn-dark border border-white rounded-5" %>
<% end %>
</div>

app/views/planets/edit.html.erb
<%= render "form", planet: @planet %>

app/views/planets/home.html.erb
<div class="search">
    <%= form_with url: root_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a planet name"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-dark rounded-5" %>
    <% end %>
</div>





<div class="cards">

    <%@planets.each do |planet|%>
    <%= link_to planet_path(planet) do %>
      <div class="card-category">
        <% if planet.photo.attached? %>
          <div class="img-card">
            <%=  cl_image_tag planet.photo.key, crop: :fit, class:"img-planet" %>
          </div>
        <% end %>
        <div class="card-text">
          <h3><%= planet.name%></h3>
          <h4><%= "Prix: #{planet.price}$ / Nuit"%></h4>
        </div>
      </div>

        <% end %>
    <%end%>
  </div>

app/views/planets/index.html.erb
<h1 class="mes-planets">Mes planets</h1>

<div class="cards">

    <%@planets.each do |planet|%>
      <%= link_to planet_path(planet) do %>
        <div class="card-category">
          <% if planet.photo.attached? %>
            <div class="img-card">
              <%=  cl_image_tag planet.photo.key, crop: :fit, class:"img-planet" %>
            </div>
          <% end %>
            <h3><%= planet.name%></h3>
            <h4><%= "Prix: #{planet.price}$ / Nuit"%></h4>
          </div>
          <% end %>
    <%end%>
  </div>

app/views/planets/new.html.erb
<%= render "form", planet: @planet %>

app/views/planets/show.html.erb
<div class="container d-flex justify-content-around align-items-center">
  <div class="picture m-5">
    <% if @planet.photo.attached? %>
    <p><%= cl_image_tag @planet.photo.key, height: 700, width: 700, crop: :fill %></p>
    <% else %>
    <p><%= image_tag 'planet-par-defaut.png', height: 700, width: 700 %></p>
    <% end %>
  </div>
  <div class="content m-5">
    <h1 class="title-planet"><%= @planet.name %></h1>
    <p class="detail-planet"><%= @planet.detail%></p>
    <p class="price-planet"><%= @planet.price%>$</p>
    <% if current_user == @planet.user %>
      <%= link_to "Edit your planet", edit_planet_path, class:"btn btn-dark border border-white rounded-5 text-decoration-none"%>
      <%= link_to "Delete", planet_path(@planet), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-dark border border-white rounded-5 text-decoration-none"%>
    <% else %>
      <%= link_to "Booking", new_planet_booking_path(@planet), class:"btn btn-dark border border-white rounded-5 text-decoration-none"%>
    <% end %>
  </div>
</div>